### Index method
GET http://localhost:3000/api/jokes

### Successfully posts a joke
POST http://localhost:3000/api/jokes
Content-Type: application/json

{
  "category_id": 1,
  "body": "The furniture store keeps calling me to come back, but all I wanted was one night stand."
}

### unsuccessfully posts a joke
POST http://localhost:3000/api/jokes
Content-Type: application/json

{
  "body": "The furniture store keeps calling me to come back, but all I wanted was one night stand."
}

### show joke id: 1
GET http://localhost:3000/api/jokes

### unsuccessfully show  show joke id: 1000
GET http://localhost:3000/api/jokes/1000

### successfully update joke id: 1
PUT http://localhost:3000/api/jokes/1
Content-Type: application/json

{
  "body": "A funny programming joke",
  "category_id": 2
}

### successfully delete joke id: 1
DELETE http://localhost:3000/api/jokes/1

### unsuccessfully delete joke id: 1000
DELETE http://localhost:3000/api/jokes/1000